### ISSUE TITLE
在项目根目录建了.env文件但是运行错误

### ISSUE THREAD

**Issue by zhangweiwei0326** [littlebutt/fubuki-iot#2]
Traceback (most recent call last):
  File "e:\www\demo\tmjl\app.py", line 4, in <module>
    Terminal.run()
  File "D:\Python3\Lib\site-packages\iot\terminal.py", line 24, in run
    Pipeline.before(**kwargs)
  File "D:\Python3\Lib\site-packages\iot\pipeline.py", line 21, in before
    Context.load_context()
  File "D:\Python3\Lib\site-packages\iot\context.py", line 28, in load_context
    cls.config.load_config()
  File "D:\Python3\Lib\site-packages\iot\config.py", line 12, in load_config
    raise KeyError("Config missing: RESOURCE_PATH")
KeyError: 'Config missing: RESOURCE_PATH'

**Comment by littlebutt** [comment]
`.env`文件里包含`RESOURCE_PATH=`了吗？根据提示应该是缺少这个key。

**Comment by zhangweiwei0326** [comment]
有的

**Comment by zhangweiwei0326** [comment]
![image](https://github.com/littlebutt/fubuki-iot/assets/5975616/4985cb59-ac8e-42f3-a813-145694bccb5f)

**Comment by zhangweiwei0326** [comment]
![image](https://github.com/littlebutt/fubuki-iot/assets/5975616/ee27ea5b-95eb-43a9-90e2-b28c9a2177ac)

**Comment by littlebutt** [comment]
我好像不能复现，是不是`dotenv`那边改了，我是0.21版本。
![image](https://github.com/littlebutt/fubuki-iot/assets/70781619/8292696d-072d-481e-9fcd-fe1964520933)

**Comment by zhangweiwei0326** [comment]
有可能噢 我的是1.0

**Comment by zhangweiwei0326** [comment]
我直接在app.py 里面打印dotenv_values() 是有值的 但在你那个config.py里面打印 是空的

**Comment by littlebutt** [comment]
我也是这样取值的，如果是依赖版本更新的问题麻烦PR一下了，谢了
![image](https://github.com/littlebutt/fubuki-iot/assets/70781619/e5161791-00b9-4e3e-9bb8-d0823947e345)
